# Configuration for `dependabot`
# See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 0 # disable dependabot
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 0 # disable dependabot
