name: Test

on:
  push:
    branches:
      - master
      - 'release/**'

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # fetch all Git history so that `changesets` can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Print stuffs
        run: echo "${{ github.ref == 'refs/heads/master' && 'New Release' || 'New Patch Release' }}"
      - name: Print stuffs 2
        run: echo "${{ github.ref }}"
      - name: Print stuffs 3
        run: echo "${{ github.base_ref }}"
