name: Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "github.event.pull_request.base.ref != 'master' || !startsWith(github.event.pull_request.title, 'Cherry-picking changes in version ')"
    steps:
      - name: Print stuffs
        run: echo "${{ startsWith(github.event.pull_request.title, 'Cherry-picking changes in version ') }}" "${{ github.event.pull_request.base.ref != 'master' || !startsWith(github.event.pull_request.title, 'Cherry-picking changes in version ') }}"
